version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}

  bot:
    image: andytakker/inclusive_dance_bot:latest
    restart: unless-stopped
    command: /wait-for-it.sh -t 15 -h db -p 5432 -- /app/start.sh
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

      PG_URL: postgresql+asyncpg://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_DB: $REDIS_DB

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

volumes:
  postgres_data:
    driver: local
