version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    command: redis-server --requirepass $REDIS_PASSWORD

  bot:
    image: andytakker/inclusive_dance_bot:latest
    restart: unless-stopped
    command: /wait-for-it.sh -t 15 -h db -p 5432 -- /app/start.sh
    environment:
      APP_REDIS_DSN: redis://:$REDIS_PASSWORD@redis:6379/1
      APP_PG_DSN: postgresql+asyncpg://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB

      APP_TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN

volumes:
  postgres_data:
    driver: local
