"""Init db

Revision ID: 5ab12cab793a
Revises:
Create Date: 2023-10-08 11:30:31.907250

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5ab12cab793a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=64), nullable=False),
        sa.Column("message", sa.String(length=4000), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__entity")),
    )
    op.create_table(
        "url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__url")),
        sa.UniqueConstraint("slug", name=op.f("uq__url__slug")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("region", sa.String(length=256), nullable=False),
        sa.Column("phone_number", sa.String(length=16), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user")),
    )
    op.create_table(
        "user_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_type")),
    )
    op.create_index(op.f("ix__user_type__name"), "user_type", ["name"], unique=False)
    op.create_table(
        "user_type_user",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk__user_type_user__user_id__user")
        ),
        sa.ForeignKeyConstraint(
            ["user_type_id"],
            ["user_type.id"],
            name=op.f("fk__user_type_user__user_type_id__user_type"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "user_type_id", name=op.f("pk__user_type_user")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_type_user")
    op.drop_index(op.f("ix__user_type__name"), table_name="user_type")
    op.drop_table("user_type")
    op.drop_table("user")
    op.drop_table("url")
    op.drop_table("entity")
    # ### end Alembic commands ###
