"""Initial commit

Revision ID: daabaf35a8a3
Revises:
Create Date: 2023-10-21 22:37:41.839949

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "daabaf35a8a3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=64), nullable=False),
        sa.Column("message", sa.String(length=4000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__entity")),
    )
    op.create_table(
        "url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__url")),
        sa.UniqueConstraint("slug", name=op.f("uq__url__slug")),
    )
    op.create_table(
        "user_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__user_type")),
    )
    op.create_index(op.f("ix__user_type__name"), "user_type", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("region", sa.String(length=256), nullable=False),
        sa.Column("phone_number", sa.String(length=16), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.Column("is_viewed", sa.Boolean(), nullable=False),
        sa.Column("viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_answered", sa.Boolean(), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk__feedback__user_id__users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__feedback")),
    )
    op.create_index(
        op.f("ix__feedback__user_id"), "feedback", ["user_id"], unique=False
    )
    op.create_table(
        "user_type_user",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk__user_type_user__user_id__users")
        ),
        sa.ForeignKeyConstraint(
            ["user_type_id"],
            ["user_type.id"],
            name=op.f("fk__user_type_user__user_type_id__user_type"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "user_type_id", name=op.f("pk__user_type_user")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_type_user")
    op.drop_index(op.f("ix__feedback__user_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_table("users")
    op.drop_index(op.f("ix__user_type__name"), table_name="user_type")
    op.drop_table("user_type")
    op.drop_table("url")
    op.drop_table("entity")
    # ### end Alembic commands ###
