name: Make release

env:
  PROJECT_NAME: inclusive_dance_bot
  GOTIFY_HOST: ${{ secrets.GOTIFY_HOST }}
  GOTIFY_APP_TOKEN: ${{ secrets.GOTIFY_APP_TOKEN }}
  GOTIFY_TITLE: Inclusive Dance Bot
  GOTIFY_MESSAGE: Checked repo ${{ github.REF_NAME }}
  GOTIFY_EVENT_NAME: ${{ github.EVENT_NAME  }}
  GOTIFY_REPOSITORY_URL: ${{ github.SERVER_URL }}/${{ github.REPOSITORY }}
  GOTIFY_ACTION_URL: ${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/actions/runs/${{ github.RUN_ID }}

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checking:
    name: Check repository
    uses: ./.github/workflows/check.yml

  build_and_push:
    name: Build and push AMD64 and ARM64 images
    needs: checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: andytakker/${{ env.PROJECT_NAME }}:latest

  notify:
    name: Notify successful CI
    needs: build_and_push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send notify
        run: python ./gotify.py
