name: Make release

env:
  PROJECT_NAME: inclusive_dance_bot
  PROJECT_TITLE: Inclusive Dance Bot

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checking:
    name: Check repository
    uses: ./.github/workflows/check.yml

  build_and_push:
    name: Build and push AMD64 and ARM64 images
    needs: checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: andytakker/${{ env.PROJECT_NAME }}:latest

      - name: Send release notification
        run: |
          curl "http://188.225.87.124/message?token=${{ secrets.GOTIFY_APP_TOKEN }}" \
            -F "title=${{ env.PROJECT_TITLE }}" \
            -F "message=Released ${{ github.SHA }} ${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/actions/runs/${{ github.RUN_ID }}" \
            -F "priority=2"
